### ISSUE TITLE
NameError: name 'SmoothedValue' is not defined，期待您的答疑！

### ISSUE THREAD

**Issue by hjj-upup** [xianghuisun/Chinese_KGQA#1]
在试跑python train.py --knowledge_dir a --qa_dir b --save_dir c --bert_name d时出现如下报错：

File "/data/Chinese_KGQA/code/TransferNet/utils.py", line 98, in __init__
    self.meters = defaultdict(SmoothedValue)
NameError: name 'SmoothedValue' is not defined

**Comment by xianghuisun** [comment]
https://github.com/shijx12/TransferNet 你可以看这个仓库的代码，TransferNet的原版代码

**Comment by hjj-upup** [comment]
好的，谢谢！

**Comment by Garethyu** [comment]
> 好的，谢谢！

请问您有解决这个问题吗？
